In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('Ecommerce Customers.csv')

In [6]:
df

Email  \
0          mstephenson@fernandez.com   
1                  hduke@hotmail.com   
2                   pallen@yahoo.com   
3            riverarebecca@gmail.com   
4      mstephens@davidson-herman.com   
5             alvareznancy@lucas.biz   
6              katherine20@yahoo.com   
7                 awatkins@yahoo.com   
8        vchurch@walter-martinez.com   
9                   bonnie69@lin.biz   
10             andrew06@peterson.com   
11            ryanwerner@freeman.biz   
12                 knelson@gmail.com   
13             wrightpeter@yahoo.com   
14             taylormason@gmail.com   
15               jstark@anderson.com   
16               wjennings@gmail.com   
17          rebecca45@hale-bauer.biz   
18           alejandro75@hotmail.com   
19            samuel46@love-west.net   
20                 megan33@gmail.com   
21                 agolden@yahoo.com   
22             vstafford@hotmail.com   
23   denise22@hernandez-townsend.com   
24            youngbarbara@yahoo.com   
25           william25@mcconnell.com   
26          ijones@schaefer-carr.net   
27             heatherhall@yahoo.com   
28           tinasmith@martinez.info   
29         chasejennifer@hotmail.com   
..                               ...   
470           kennethperry@bowen.org   
471               prussell@lopez.com   
472            mosleyjacob@yahoo.com   
473                  rhaas@yahoo.com   
474        antonioharris@hotmail.com   
475           austinthomas@gmail.com   
476            bethsullivan@reed.net   
477              ncummings@yahoo.com   
478                hking@hotmail.com   
479             annstone@hotmail.com   
480        christopher44@hotmail.com   
481       autumn88@mendoza-mills.com   
482                dhudson@ramos.net   
483               egomez@hotmail.com   
484    kimberlyruiz@smith-gordon.com   
485          mooremichelle@logan.com   
486                aaron22@gmail.com   
487       michelleshepherd@price.com   
488                zscott@wright.com   
489              tracy79@wheeler.net   
490              brian28@sanchez.org   
491       leonardhancock@hotmail.com   
492       davidsonkathleen@gmail.com   
493              nathan84@lowery.net   
494            kellydeborah@chan.biz   
495     lewisjessica@craig-evans.com   
496              katrina56@gmail.com   
497               dale88@hotmail.com   
498              cwilson@hotmail.com   
499        hannahwilson@davidson.com   

                                               Address            Avatar  \
0         835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1       4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2    24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3     1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4    14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
5    645 Martha Park Apt. 611\nJeffreychester, MN 6...       FloralWhite   
6    68388 Reyes Lights Suite 692\nJosephbury, WV 9...     DarkSlateBlue   
7                Unit 6538 Box 8980\nDPO AP 09026-4941              Aqua   
8               860 Lee Key\nWest Debra, SD 97450-0495            Salmon   
9                PSC 2734, Box 5255\nAPO AA 98456-7482             Brown   
10   26104 Alexander Groves\nAlexandriaport, WY 282...            Tomato   
11               Unit 2413 Box 0347\nDPO AA 07580-2652            Tomato   
12   6705 Miller Orchard Suite 186\nLake Shanestad,...         RoyalBlue   
13    05302 Dunlap Ferry\nNew Stephaniehaven, MP 42268            Bisque   
14   7773 Powell Springs Suite 190\nSamanthaland, N...          DarkBlue   
15   49558 Ramirez Road Suite 399\nPhillipstad, OH ...              Peru   
16         6362 Wilson Mountain\nJohnsonfurt, GA 15169        PowderBlue   
17                8982 Burton Row\nWilsonton, PW 88606         OliveDrab   
18   64475 Andre Club Apt. 795\nPort Dannytown, PW ...              Cyan   
19   544 Alexander Heights Sui

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
Email                   500 non-null object
Address                 500 non-null object
Avatar                  500 non-null object
Avg. Session Length     500 non-null float64
Time on App             500 non-null float64
Time on Website         500 non-null float64
Length of Membership    500 non-null float64
Yearly Amount Spent     500 non-null float64
dtypes: float64(5), object(3)
memory usage: 31.3+ KB


In [8]:
df.drop(['Email','Address','Avatar'],axis=1,inplace=True)

In [9]:
df.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [10]:
df.corr()

Avg. Session Length  Time on App  Time on Website  \
Avg. Session Length              1.000000    -0.027826        -0.034987   
Time on App                     -0.027826     1.000000         0.082388   
Time on Website                 -0.034987     0.082388         1.000000   
Length of Membership             0.060247     0.029143        -0.047582   
Yearly Amount Spent              0.355088     0.499328        -0.002641   

                      Length of Membership  Yearly Amount Spent  
Avg. Session Length               0.060247             0.355088  
Time on App                       0.029143             0.499328  
Time on Website                  -0.047582            -0.002641  
Length of Membership              1.000000             0.809084  
Yearly Amount Spent               0.809084             1.000000

In [11]:
y=(df['Yearly Amount Spent'])

In [12]:
y.head()

0    587.951054
1    392.204933
2    487.547505
3    581.852344
4    599.406092
Name: Yearly Amount Spent, dtype: float64

In [13]:
df.drop('Yearly Amount Spent',axis=1,inplace=True)

In [14]:
df.head()

Avg. Session Length  Time on App  Time on Website  Length of Membership
0            34.497268    12.655651        39.577668              4.082621
1            31.926272    11.109461        37.268959              2.664034
2            33.000915    11.330278        37.110597              4.104543
3            34.305557    13.717514        36.721283              3.120179
4            33.330673    12.795189        37.536653              4.446308

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(df,y,test_size=0.2)

In [17]:
l_reg=LinearRegression()

In [18]:
l_reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
print(l_reg.coef_)
print(l_reg.intercept_)

[26.06755562 38.82037442  0.15167969 61.67105594]
-1053.7703380373312


In [20]:
y_pred=l_reg.predict(X_train)

In [21]:
l_reg.score(X_train,Y_train)

0.9826519595384228

In [23]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=l_reg, X=X_train, y=Y_train, cv=10)
model_accuracy = accuracies.mean()
model_standard_deviation = accuracies.std()

In [24]:
accuracies

array([0.97977005, 0.97863275, 0.98503935, 0.98422501, 0.98977042,
       0.97843172, 0.97521277, 0.97946991, 0.98391294, 0.97302704])

In [25]:
model_accuracy

0.9807491960193524

In [26]:
model_standard_deviation

0.004739277852774333

In [27]:
y_pred

array([590.63579745, 518.67381557, 525.73917796, 534.30800372,
       548.82723984, 537.62796765, 512.51897083, 657.69028508,
       473.37146882, 458.02655498, 493.12490393, 383.58168514,
       652.25232554, 432.18376383, 716.33485711, 573.24681227,
       541.01824805, 510.03492585, 562.75331046, 460.60086809,
       588.50997322, 725.44031033, 450.61952855, 526.77344468,
       440.52090324, 590.36644744, 558.28493884, 548.17113301,
       694.14348695, 463.10180361, 611.27974285, 456.27152416,
       484.8104455 , 284.22567776, 476.49771363, 539.76148897,
       519.20551592, 379.68970404, 467.57564962, 486.38396243,
       552.68258891, 512.60567143, 474.68260205, 523.46895272,
       455.10006659, 648.98886039, 520.51736776, 476.98985701,
       569.55377846, 524.40889273, 461.22222086, 568.23813182,
       447.19310425, 569.2363286 , 589.03762403, 556.87652449,
       418.81638642, 501.5915688 , 379.87722092, 555.14025321,
       551.79204802, 523.26538284, 411.55413366, 493.32

In [28]:
import statsmodels.api as sm
ols=sm.OLS(endog=Y_test,exog=X_test)
result=ols.fit()
print(result.summary())

                             OLS Regression Results                            
Dep. Variable:     Yearly Amount Spent   R-squared:                       0.998
Model:                             OLS   Adj. R-squared:                  0.998
Method:                  Least Squares   F-statistic:                 1.388e+04
Date:                 Mon, 08 Apr 2019   Prob (F-statistic):          1.17e-131
Time:                         23:19:26   Log-Likelihood:                -443.93
No. Observations:                  100   AIC:                             895.9
Df Residuals:                       96   BIC:                             906.3
Df Model:                            4                                         
Covariance Type:             nonrobust                                         
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Avg. Session Length   

In [29]:
y_pred_test=l_reg.predict(X_test)

In [30]:
l_reg.score(X_test,Y_test)

0.9891820053530143